### ISSUE TITLE
build failed on ubuntu 18.04 LTS(docker image)

### ISSUE THREAD

**Issue by minhyuk** [facelessuser/backrefs#102]
Hi. I'm using a python library called wcmatch, and I'm having a build problem with the related dependency item, backrefs.

I think the problem appears in ubuntu 18.04.
And The error message looks like this:

What did I do wrong?
```
/# pip3 install backrefs
...<skipped>...
Skipping: found /tmp/pip-build-51bzznq8/backrefs/tools/unicodedata/9.0.0/BidiBrackets.txt
 ========Unicode Tables========
    Building: General Category
    Building: Blocks
    Traceback (most recent call last):
      File "/tmp/pip-build-51bzznq8/backrefs/setup.py", line 69, in generate_unicode_table
        'backrefs', 'uniprops', 'unidata'
      File "/tmp/pip-build-51bzznq8/backrefs/tools/unipropgen.py", line 1233, in build_tables
        build_unicode_property_table(output)
      File "/tmp/pip-build-51bzznq8/backrefs/tools/unipropgen.py", line 1219, in build_unicode_property_table
        gen_properties(output)
      File "/tmp/pip-build-51bzznq8/backrefs/tools/unipropgen.py", line 1045, in gen_properties
        gen_blocks(files['blk'], ascii_props, append, prefix)
      File "/tmp/pip-build-51bzznq8/backrefs/tools/unipropgen.py", line 173, in gen_blocks
        for line in uf:
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 59: ordinal not in range(128)

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-51bzznq8/backrefs/setup.py", line 91, in <module>
        generate_unicode_table()
      File "/tmp/pip-build-51bzznq8/backrefs/setup.py", line 78, in generate_unicode_table
        assert not fail, "Failed uniprops.py generation!"
    AssertionError: Failed uniprops.py generation!
```

**Comment by facelessuser** [comment]
@minhyuk, generally, the Unicode files from which the tables are built from have ASCII characters in them, but it may be possible that a few of them didn't, and the systems on which I've tested and installed on pick a default encoding that works.  Your system maybe isn't picking a default encoding that can handle them.

If this is the problem, I need to update the Unicode property table to explicitly read those files with UTF-8.  I'll check and see if that is the issue.

**Comment by facelessuser** [comment]
Try this out:

```
python3.6 -m pip install -U git+https://github.com/facelessuser/backrefs@unicode-table-read
```

I set up a branch that should read in the Unicode property files as UTF-8 when generating the tables.  Let me know if that installs okay. If it does, I may need to make a new release with these changes.

**Comment by minhyuk** [comment]
> Try this out:
> 
> ```
> python3.6 -m pip install -U git+https://github.com/facelessuser/backrefs@unicode-table-read
> ```
> I set up a branch that should read in the Unicode property files as UTF-8 when generating the tables. Let me know if that installs okay. If it does, I may need to make a new release with these changes.

Yes!! It works!
Please let me know if you want to check more.
thank you.

**Comment by facelessuser** [comment]
Perfect! I'll try and make a release tomorrow (it's late here).

**Comment by minhyuk** [comment]
:) thanks, Anyway, you save my day! have good night~

**Comment by facelessuser** [comment]
A new release has been made: https://pypi.org/project/backrefs/.

I'm surprised it has gone this long without this issue coming up sooner, but it is fixed now 🙂 .
