### ISSUE TITLE
Python 3.13 Support

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/backrefs#185]
We should start getting support for 3.13 ready as it is entering beta stage.

Beta may change final Unicodedata used before final release, but we need to make sure everything is currently in place and working anticipating Unicode 15.1.0 support for now. Before official Py 3.13 release, we'll make sure we support whatever is in the final release.

**Comment by mgorny** [comment]
Could you make a new release with the new unicodedata archive, please?

**Comment by facelessuser** [comment]
I guess we can make an early release ahead of official Python 3.13. It's already on main and working.

**Comment by facelessuser** [comment]
A new release has been tagged. If they end up having a refresh of unicodedata before the official release, there will need to be another update.

**Comment by mgorny** [comment]
Thanks a lot! I can confirm that the new version installs and passes tests on 3.13.0b2.
