### ISSUE TITLE
Possibly include `\R` references (regex only).

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/backrefs#26]
These may be useful as `\X` is great for capturing things like `ṗ` as a single character.  `\R` is a generic line break.

The idea of `\X` seems pretty useful.  And generally `\R` is a nice general shortcut to handle all line breaks.

For non-Unicode we have no need of `\X`, and `\R` would omit Unicode chars.

```
\R = (?>\r\n|\n|\x0b|\f|\r|\x85)
```

For Unicode

```
\X = (?>\PM\pM*)
\R = (?>\r\n|\n|\x0b|\f|\r|\x85|\u2028|\u2029)
```

I'm still thinking about this, but since re does not support atomic groups currently, this would have to be regex only.

**Comment by facelessuser** [comment]
Grapheme support is already in Regex, so no need to bother with that.

**Comment by serhiy-storchaka** [comment]
The `\R`support is in regex too. There is a plan of adding its support in re, but we first should add a support of other features.

**Comment by facelessuser** [comment]
That is great.  I look forward to seeing it.  It sounds like there is a lot of good changes coming to Re 🙂 .
