### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/backrefs#7]
Looks like we aren't going to get lucky and have 3.7 just work ☹️ .  I'm trying to get acquainted with these issues early so when 3.7 goes live, I'll be ready.

Issues seem to be be contained to `bre` and seem to deal with escaped characters again.  Not sure what Python is doing in regards to escapes, but it looks like there is more work to be done:

```
                else:
                    try:
>                       this = chr(ESCAPES[this][1])
E                       KeyError: '\\c'
```

**Comment by facelessuser** [comment]
I understand what is happening now.  The re template parser is choking on unexpected replace back references.  We only use `\c`, `\l`, and `\C...\E` and `\L...\E` which are used for capitalizing replace chars or spans.  I may have to implement a more creative way to accomplish this.

**Comment by facelessuser** [comment]
It should be noted that only `re` has issues with this.  The regex module still handles this with no issues.

**Comment by facelessuser** [comment]
This is tricky as it seems that `re` arbitrarily fails on any escape that is followed by an ASCII character in parse_template.  Why only ASCII, I'm not sure.  So we need to make sure they are escaped in a way that passes, but be able to find them afterwards.

**Comment by facelessuser** [comment]
So, after thinking about this, I think the best way to approach this is to preprocess and apply upper and lower case back references to the template before sending through `sre_parse.parse_template`. We can change case of literals, and then take note of the group slots that we must change on replace.  This will allow us to completely eliminate the need to pass our back references through `sre_parse`.  By time `sre_parse` gets the template, it will be transformed into a standard template and we should have all the information we need.

This is probably the way it should have always been, oh well.  This will be a bit of work, but I'm glad I caught it now rather than later.  At least now there is a good chance I'll have this done by 3.7 release.

**Comment by facelessuser** [comment]
This is now working on 3.7 dev.

**Comment by serhiy-storchaka** [comment]
> Why only ASCII, I'm not sure.

Because giving new meaning to escape sequences consisting of a backslash following an ASCII letter is a safe way to introduce new features. It is possible that special escape sequences `\x`, `\u`, `\U`, `\N` etc could be supported in future in re replacement strings. This can leads to producing unexpected results if they are silently accepted in previous versions. Raising deprecation warnings in 3.5 and 3.6 and errors in 3.7 will allow to add new escape sequences in 3.8 or 3.9 with minimal harm. This is a long term plan.

**Comment by facelessuser** [comment]
@serhiy-storchaka Thanks for the explanation!  Wasn't sure why the change occurred, but that makes sense.  I've avoiding that path now, so I shouldn't run into the issue anymore, but it is nice know.
